# Generated by Django 5.0 on 2024-07-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='위도', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='경도', max_digits=9)),
                ('state_province', models.CharField(help_text='시/도', max_length=100)),
                ('city_county', models.CharField(help_text='시/군/구', max_length=100)),
                ('town_village', models.CharField(help_text='읍/면/동', max_length=100)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
