# Generated by Django 5.0 on 2024-07-24 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='city_county',
            new_name='city_country',
        ),
    ]
