# Generated by Django 5.0 on 2024-07-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='file',
            field=models.FileField(default='', upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
